#!/usr/bin/env python3
"""
fix_for_vegas.py v3
Fixes FCP XML generated by auto-editor to be compatible with Vegas Pro.
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def fix_fcp_xml_for_vegas(input_path: str, output_path: str = None):
    ET.register_namespace("", "")
    tree = ET.parse(input_path)
    root = tree.getroot()

    fixes = 0

    # Fix 1: Add missing format attributes
    required_format_attrs = {
        "fieldOrder": "none",
        "pixelAspect": "square",
        "colorDepth": "24",
    }
    for fmt in root.iter("format"):
        for attr, default in required_format_attrs.items():
            if fmt.get(attr) is None:
                fmt.set(attr, default)
                fixes += 1

    # Fix 2: samplecharacteristics
    for sc in root.iter("samplecharacteristics"):
        if sc.find("samplerate") is None:
            ET.SubElement(sc, "samplerate").text = "48000"
            fixes += 1
        if sc.find("depth") is None:
            ET.SubElement(sc, "depth").text = "16"
            fixes += 1

    # Fix 3: Remove empty <pathurl> tags
    for fileref in root.iter("file"):
        pathurl = fileref.find("pathurl")
        if pathurl is not None and (pathurl.text is None or pathurl.text.strip() == ""):
            fileref.remove(pathurl)
            fixes += 1

    # Fix 4: Remove <link> elements — causes TrackEventGroup null ref in Vegas
    for clipitem in root.iter("clipitem"):
        for link in list(clipitem.findall("link")):
            clipitem.remove(link)
            fixes += 1

    # Fix 5: Reset audio gain to 0dB on all clipitems
    # Vegas reads <audio><level> or <filter> gain — reset everything to 0
    for clipitem in root.iter("clipitem"):
        # Remove audio filters that boost gain
        for filter_el in list(clipitem.findall("filter")):
            effect = filter_el.find("effect")
            if effect is not None:
                effecttype = effect.find("effecttype")
                if effecttype is not None and effecttype.text in ("audiolevels", "audio"):
                    clipitem.remove(filter_el)
                    fixes += 1
        # Reset <audio><level> if present
        audio_el = clipitem.find("audio")
        if audio_el is not None:
            level_el = audio_el.find("level")
            if level_el is not None:
                level_el.text = "1"  # 1 = 0dB in FCP XML
                fixes += 1

    # Fix 6: Keep only ONE audio track per sequence (remove duplicates)
    for sequence in root.iter("sequence"):
        media = sequence.find("media")
        if media is not None:
            audio_tracks_parent = media.find("audio")
            if audio_tracks_parent is not None:
                all_tracks = audio_tracks_parent.findall("track")
                # Keep only first track, remove the rest
                if len(all_tracks) > 1:
                    for extra_track in all_tracks[1:]:
                        audio_tracks_parent.remove(extra_track)
                        fixes += 1

    # Fix 7: Ensure <media> has <video> and <audio> blocks
    for sequence in root.iter("sequence"):
        media = sequence.find("media")
        if media is not None:
            if media.find("video") is None:
                ET.SubElement(media, "video")
                fixes += 1
            if media.find("audio") is None:
                ET.SubElement(media, "audio")
                fixes += 1

    # Fix 8: Ensure clipitem required fields
    for clipitem in root.iter("clipitem"):
        if clipitem.find("name") is None:
            ET.SubElement(clipitem, "name").text = "clip"
            fixes += 1
        for tag in ["in", "out", "start", "end"]:
            el = clipitem.find(tag)
            if el is not None and (el.text is None or el.text.strip() == ""):
                el.text = "0"
                fixes += 1

    # Fix 9: Remove empty <track> elements
    for track_parent in list(root.iter("video")) + list(root.iter("audio")):
        for track in list(track_parent.findall("track")):
            if len(list(track)) == 0:
                track_parent.remove(track)
                fixes += 1

    if output_path is None:
        p = Path(input_path)
        output_path = str(p.parent / (p.stem + "_vegas" + p.suffix))

    tree.write(output_path, encoding="utf-8", xml_declaration=True)
    print(f"\nDone! Applied fixes: {fixes}")
    print(f"Output file: {output_path}")
    print("Import to Vegas Pro: File -> Import -> Final Cut Pro 7 XML")


def clean_path(path: str) -> str:
    path = path.strip()
    if (path.startswith('"') and path.endswith('"')) or \
       (path.startswith("'") and path.endswith("'")):
        path = path[1:-1]
    return path.strip()


if __name__ == "__main__":
    print("=" * 50)
    print("   FCP XML -> Vegas Pro Fixer  v3")
    print("=" * 50)

    if len(sys.argv) >= 2:
        input_path = clean_path(sys.argv[1])
    else:
        raw = input("\nPath to XML file (from auto-editor): ")
        input_path = clean_path(raw)

    if not Path(input_path).exists():
        print(f"\nError: File not found:\n  {input_path}")
        input("\nPress Enter to exit...")
        sys.exit(1)

    p = Path(input_path)
    default_output = str(p.parent / (p.stem + "_vegas" + p.suffix))

    if len(sys.argv) >= 3:
        output_path = clean_path(sys.argv[2])
    else:
        print(f"\nDefault output file:\n  {default_output}")
        custom = input("Custom path or Enter for default: ").strip()
        output_path = clean_path(custom) if custom else None

    try:
        fix_fcp_xml_for_vegas(input_path, output_path)
    except ET.ParseError as e:
        print(f"\nXML parsing error: {e}")
    except Exception as e:
        print(f"\nError: {e}")

    input("\nPress Enter to exit...")
